/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";

export const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>

        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>post</div>
    </>
  );
};

export default SinglePostPage;